const classroomConstants = {
    GET_CLASSROOM_LIST_LOADING: "GET_CLASSROOM_LIST_LOADING",
    GET_CLASSROOM_LIST_SUCCESS: "GET_CLASSROOM_LIST_SUCCESS",
    GET_CLASSROOM_LIST_FAIL: "GET_CLASSROOM_LIST_FAIL",
  
    GET_CLASSROOM_LOADING: "GET_CLASSROOM_LOADING",
    GET_CLASSROOM_SUCCESS: "GET_CLASSROOM_SUCCESS",
    GET_CLASSROOM_FAIL: "GET_CLASSROOM_FAIL",
  
    CREATE_CLASSROOM_LOADING: "CREATE_CLASSROOM_LOADING",
    CREATE_CLASSROOM_SUCCESS: "CREATE_CLASSROOM_SUCCESS",
    CREATE_CLASSROOM_FAIL: "CREATE_CLASSROOM_FAIL",
  
    UPDATE_CLASSROOM_LOADING: "UPDATE_CLASSROOM_LOADING",
    UPDATE_CLASSROOM_SUCCESS: "UPDATE_CLASSROOM_SUCCESS",
    UPDATE_CLASSROOM_FAIL: "UPDATE_CLASSROOM_FAIL",
  
    DELETE_CLASSROOM_LOADING: "DELETE_CLASSROOM_LOADING",
    DELETE_CLASSROOM_SUCCESS: "DELETE_CLASSROOM_SUCCESS",
    DELETE_CLASSROOM_FAIL: "DELETE_CLASSROOM_FAIL",
  };
  
  export default classroomConstants;