const lessonConstants = {
    GET_LESSON_LIST_LOADING: "GET_LESSON_LIST_LOADING",
    GET_LESSON_LIST_SUCCESS: "GET_LESSON_LIST_SUCCESS",
    GET_LESSON_LIST_FAIL: "GET_LESSON_LIST_FAIL",
  
    GET_LESSON_LOADING: "GET_LESSON_LOADING",
    GET_LESSON_SUCCESS: "GET_LESSON_SUCCESS",
    GET_LESSON_FAIL: "GET_LESSON_FAIL",
  
    CREATE_LESSON_LOADING: "CREATE_LESSON_LOADING",
    CREATE_LESSON_SUCCESS: "CREATE_LESSON_SUCCESS",
    CREATE_LESSON_FAIL: "CREATE_LESSON_FAIL",
  
    UPDATE_LESSON_LOADING: "UPDATE_LESSON_LOADING",
    UPDATE_LESSON_SUCCESS: "UPDATE_LESSON_SUCCESS",
    UPDATE_LESSON_FAIL: "UPDATE_LESSON_FAIL",
  
    DELETE_LESSON_LOADING: "DELETE_LESSON_LOADING",
    DELETE_LESSON_SUCCESS: "DELETE_LESSON_SUCCESS",
    DELETE_LESSON_FAIL: "DELETE_LESSON_FAIL",
  };
  
  export default lessonConstants;