const roomConstants = {
    GET_ROOM_LIST_LOADING: "GET_ROOM_LIST_LOADING",
    GET_ROOM_LIST_SUCCESS: "GET_ROOM_LIST_SUCCESS",
    GET_ROOM_LIST_FAIL: "GET_ROOM_LIST_FAIL",
  
    GET_ROOM_LOADING: "GET_ROOM_LOADING",
    GET_ROOM_SUCCESS: "GET_ROOM_SUCCESS",
    GET_ROOM_FAIL: "GET_ROOM_FAIL",
  
    CREATE_ROOM_LOADING: "CREATE_ROOM_LOADING",
    CREATE_ROOM_SUCCESS: "CREATE_ROOM_SUCCESS",
    CREATE_ROOM_FAIL: "CREATE_ROOM_FAIL",
  
    UPDATE_ROOM_LOADING: "UPDATE_ROOM_LOADING",
    UPDATE_ROOM_SUCCESS: "UPDATE_ROOM_SUCCESS",
    UPDATE_ROOM_FAIL: "UPDATE_ROOM_FAIL",
  
    DELETE_ROOM_LOADING: "DELETE_ROOM_LOADING",
    DELETE_ROOM_SUCCESS: "DELETE_ROOM_SUCCESS",
    DELETE_ROOM_FAIL: "DELETE_ROOM_FAIL",

    CLEAR_ROOM_MESSAGE: "CLEAR_ROOM_MESSAGE:",
    CLEAR_ROOM_LIST_MESSAGE: "CLEAR_ROOM_LIST_MESSAGE:",
  };
  
  export default roomConstants;