const timetableConstants = {
    GET_TIMETABLE_LIST_LOADING: "GET_TIMETABLE_LIST_LOADING",
    GET_TIMETABLE_LIST_SUCCESS: "GET_TIMETABLE_LIST_SUCCESS",
    GET_TIMETABLE_LIST_FAIL: "GET_TIMETABLE_LIST_FAIL",
  
    GET_TIMETABLE_LOADING: "GET_TIMETABLE_LOADING",
    GET_TIMETABLE_SUCCESS: "GET_TIMETABLE_SUCCESS",
    GET_TIMETABLE_FAIL: "GET_TIMETABLE_FAIL",
  
    CREATE_TIMETABLE_LOADING: "CREATE_TIMETABLE_LOADING",
    CREATE_TIMETABLE_SUCCESS: "CREATE_TIMETABLE_SUCCESS",
    CREATE_TIMETABLE_FAIL: "CREATE_TIMETABLE_FAIL",
  
    UPDATE_TIMETABLE_LOADING: "UPDATE_TIMETABLE_LOADING",
    UPDATE_TIMETABLE_SUCCESS: "UPDATE_TIMETABLE_SUCCESS",
    UPDATE_TIMETABLE_FAIL: "UPDATE_TIMETABLE_FAIL",
  
    DELETE_TIMETABLE_LOADING: "DELETE_TIMETABLE_LOADING",
    DELETE_TIMETABLE_SUCCESS: "DELETE_TIMETABLE_SUCCESS",
    DELETE_TIMETABLE_FAIL: "DELETE_TIMETABLE_FAIL",

    CLEAR_TIMETABLE_MESSAGE: "CLEAR_TIMETABLE_MESSAGE:",
    CLEAR_TIMETABLE_LIST_MESSAGE: "CLEAR_TIMETABLE_LIST_MESSAGE:",
  };
  
  export default timetableConstants;