const timeslotConstants = {
    GET_TIMESLOT_LIST_LOADING: "GET_TIMESLOT_LIST_LOADING",
    GET_TIMESLOT_LIST_SUCCESS: "GET_TIMESLOT_LIST_SUCCESS",
    GET_TIMESLOT_LIST_FAIL: "GET_TIMESLOT_LIST_FAIL",
  
    GET_TIMESLOT_LOADING: "GET_TIMESLOT_LOADING",
    GET_TIMESLOT_SUCCESS: "GET_TIMESLOT_SUCCESS",
    GET_TIMESLOT_FAIL: "GET_TIMESLOT_FAIL",
  
    CREATE_TIMESLOT_LOADING: "CREATE_TIMESLOT_LOADING",
    CREATE_TIMESLOT_SUCCESS: "CREATE_TIMESLOT_SUCCESS",
    CREATE_TIMESLOT_FAIL: "CREATE_TIMESLOT_FAIL",
  
    UPDATE_TIMESLOT_LOADING: "UPDATE_TIMESLOT_LOADING",
    UPDATE_TIMESLOT_SUCCESS: "UPDATE_TIMESLOT_SUCCESS",
    UPDATE_TIMESLOT_FAIL: "UPDATE_TIMESLOT_FAIL",
  
    DELETE_TIMESLOT_LOADING: "DELETE_TIMESLOT_LOADING",
    DELETE_TIMESLOT_SUCCESS: "DELETE_TIMESLOT_SUCCESS",
    DELETE_TIMESLOT_FAIL: "DELETE_TIMESLOT_FAIL",
  };
  
  export default timeslotConstants;